[package]
name = "giallo-kak"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4"
giallo = { version = "0.2.2", features = ["dump"] }
libc = "0.2"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simple_logger = "5"
toml = "0.8"
which = "6"
